// Code generated by go-swagger; DO NOT EDIT.

package misc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetMockedOKCode is the HTTP code returned for type GetMockedOK
const GetMockedOKCode int = 200

/*GetMockedOK get mocked o k

swagger:response getMockedOK
*/
type GetMockedOK struct {

	/*
	  In: Body
	*/
	Payload GetMockedOKBody `json:"body,omitempty"`
}

// NewGetMockedOK creates GetMockedOK with default headers values
func NewGetMockedOK() *GetMockedOK {
	return &GetMockedOK{}
}

// WithPayload adds the payload to the get mocked o k response
func (o *GetMockedOK) WithPayload(payload GetMockedOKBody) *GetMockedOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get mocked o k response
func (o *GetMockedOK) SetPayload(payload GetMockedOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMockedOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
