// Code generated by go-swagger; DO NOT EDIT.

/*Package restapi To-do Demo

## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left. ## Welcome

This is a place to put general notes and extra information, for internal use.

To get started designing/documenting this API, select a version on the left.


    Schemes:
      http
    Host: todos.stoplight.io
    BasePath: /
    Version: 1.0

    Consumes:
    - application/json


    Produces:
    - application/json


swagger:meta
*/
package restapi
