// Code generated by go-swagger; DO NOT EDIT.

package todos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	errors "github.com/go-openapi/errors"
	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	validate "github.com/go-openapi/validate"
)

// PutTodosHandlerFunc turns a function with the right signature into a put todos handler
type PutTodosHandlerFunc func(PutTodosParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PutTodosHandlerFunc) Handle(params PutTodosParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PutTodosHandler interface for that can handle valid put todos params
type PutTodosHandler interface {
	Handle(PutTodosParams, interface{}) middleware.Responder
}

// NewPutTodos creates a new http.Handler for the put todos operation
func NewPutTodos(ctx *middleware.Context, handler PutTodosHandler) *PutTodos {
	return &PutTodos{Context: ctx, Handler: handler}
}

/*PutTodos swagger:route PUT /todos/{todoId} Todos putTodos

Update Todo

*/
type PutTodos struct {
	Context *middleware.Context
	Handler PutTodosHandler
}

func (o *PutTodos) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutTodosParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PutTodosForbiddenBody put todos forbidden body
// swagger:model PutTodosForbiddenBody
type PutTodosForbiddenBody interface{}

// PutTodosInternalServerErrorBody put todos internal server error body
// swagger:model PutTodosInternalServerErrorBody
type PutTodosInternalServerErrorBody interface{}

// PutTodosNotFoundBody put todos not found body
// swagger:model PutTodosNotFoundBody
type PutTodosNotFoundBody struct {

	// error
	// Required: true
	Error *string `json:"error"`

	// status
	// Required: true
	Status *string `json:"status"`
}

// Validate validates this put todos not found body
func (o *PutTodosNotFoundBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PutTodosNotFoundBody) validateError(formats strfmt.Registry) error {

	if err := validate.Required("putTodosNotFound"+"."+"error", "body", o.Error); err != nil {
		return err
	}

	return nil
}

func (o *PutTodosNotFoundBody) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("putTodosNotFound"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PutTodosNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PutTodosNotFoundBody) UnmarshalBinary(b []byte) error {
	var res PutTodosNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// PutTodosUnauthorizedBody put todos unauthorized body
// swagger:model PutTodosUnauthorizedBody
type PutTodosUnauthorizedBody interface{}
