// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TodoFull Todo Full
// swagger:model todo-full
type TodoFull struct {
	TodoPartial

	// completed at
	CompletedAt strfmt.DateTime `json:"completed_at,omitempty"`

	// created at
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// id
	// Required: true
	ID *int64 `json:"id"`

	// updated at
	UpdatedAt strfmt.DateTime `json:"updated_at,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *TodoFull) UnmarshalJSON(raw []byte) error {

	var aO0 TodoPartial
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.TodoPartial = aO0

	var data struct {
		CompletedAt strfmt.DateTime `json:"completed_at,omitempty"`

		CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

		ID *int64 `json:"id"`

		UpdatedAt strfmt.DateTime `json:"updated_at,omitempty"`
	}
	if err := swag.ReadJSON(raw, &data); err != nil {
		return err
	}

	m.CompletedAt = data.CompletedAt

	m.CreatedAt = data.CreatedAt

	m.ID = data.ID

	m.UpdatedAt = data.UpdatedAt

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m TodoFull) MarshalJSON() ([]byte, error) {
	var _parts [][]byte

	aO0, err := swag.WriteJSON(m.TodoPartial)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	var data struct {
		CompletedAt strfmt.DateTime `json:"completed_at,omitempty"`

		CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

		ID *int64 `json:"id"`

		UpdatedAt strfmt.DateTime `json:"updated_at,omitempty"`
	}

	data.CompletedAt = m.CompletedAt

	data.CreatedAt = m.CreatedAt

	data.ID = m.ID

	data.UpdatedAt = m.UpdatedAt

	jsonData, err := swag.WriteJSON(data)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, jsonData)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this todo full
func (m *TodoFull) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.TodoPartial.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TodoFull) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TodoFull) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TodoFull) UnmarshalBinary(b []byte) error {
	var res TodoFull
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
